### ISSUE TITLE
Error on fresh startup

### ISSUE THREAD

**Issue by SteveEdson** [pducharme/UniFi-Video-Controller#164]
I'm trying to get this image up and running, but I'm receiving the error:

<details>
<summary>Stack trace</summary>
<pre>
<code>
Cannot locate library for VM dcevm (skipping)
Java Home located in /usr/lib/jvm/java-8-openjdk-amd64/jre
+-- DUMPING JAVA HOME STRUCTURE ------------------------
| Java Home:       "/usr/lib/jvm/java-8-openjdk-amd64/jre"
| Java VM Config.: "/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/jvm.cfg"
| Found JVMs:      1
| JVM Name:        "server"
|                  "/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so"
+-------------------------------------------------------
Running w/ LD_LIBRARY_PATH=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64
redirecting stdout to /dev/null and stderr to /dev/null
Switching umask back to 022 from 077
done.
Waiting for mongodb to come online...Attemtping to load library /lib64/libcap.so.2
Attemtping to load library /lib64/libcap.so.1
Attemtping to load library /lib64/libcap.so
Attemtping to load library /usr/lib64/libcap.so.2
Attemtping to load library /usr/lib64/libcap.so.1
Attemtping to load library /usr/lib64/libcap.so
Attemtping to load library /lib/libcap.so.2
Attemtping to load library /lib/libcap.so.1
Attemtping to load library /lib/libcap.so
Attemtping to load library /usr/lib/libcap.so.2
Attemtping to load library /usr/lib/libcap.so.1
Attemtping to load library /usr/lib/libcap.so
Attemtping to load library libcap.so.2
loaded cap_free from libcap.
loaded cap_init from libcap.
loaded cap_clear from libcap.
loaded cap_get_flag from libcap.
loaded cap_set_flag from libcap.
loaded cap_set_proc from libcap.
increased capability set.
user changed to 'unifi-video'
decreased capability set to min required.
Using default JVM in /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
Attemtping to load library /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
JVM library /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so loaded
JVM library entry point found (0x602CD310)
+-- DUMPING JAVA VM CREATION ARGUMENTS -----------------
| Version:                       0x010004
| Ignore Unrecognized Arguments: True
| Extra options:                 18
|   "-Djava.class.path=/usr/share/java/commons-daemon.jar:/usr/lib/unifi-video/lib/airvision.jar" (0x00000000)
|   "-Dav.tempdir=/var/cache/unifi-video" (0x00000000)
|   "-Djava.security.egd=file:/dev/./urandom" (0x00000000)
|   "-Xmx239M" (0x00000000)
|   "-Xss512K" (0x00000000)
|   "-XX:+HeapDumpOnOutOfMemoryError" (0x00000000)
|   "-XX:+UseG1GC" (0x00000000)
|   "-XX:+UseStringDeduplication" (0x00000000)
|   "-XX:MaxMetaspaceSize=1024M" (0x00000000)
|   "-Djava.library.path=/usr/lib/unifi-video/lib" (0x00000000)
|   "-Djava.awt.headless=true" (0x00000000)
|   "-Djavax.net.ssl.trustStore=/usr/lib/unifi-video/data/ufv-truststore" (0x00000000)
|   "-Dfile.encoding=UTF-8" (0x00000000)
|   "-Dcom.sun.management.jmxremote" (0x00000000)
|   "-Dcom.sun.management.jmxremote.ssl=false" (0x00000000)
|   "-Dcom.sun.management.jmxremote.authenticate=false" (0x00000000)
|   "-Dcom.sun.management.jmxremote.port=7654" (0x00000000)
|   "-Djava.rmi.server.hostname=172.17.0.2" (0x00000000)
+-------------------------------------------------------
| Internal options:              4
|   "-Dcommons.daemon.process.id=97" (0x00000000)
|   "-Dcommons.daemon.process.parent=96" (0x00000000)
|   "-Dcommons.daemon.version=1.0.15-dev" (0x00000000)
|   "abort" (0x5d34d4e0)
+-------------------------------------------------------
Java VM created successfully
Class org/apache/commons/daemon/support/DaemonLoader found
Native methods registered
java_init done
Daemon loading...
2019-10-31 11:00:56,914 ERROR Unable to locate appender ConsoleAppender for logger
Daemon loaded successfully
java_load done
dropped capabilities.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.commons.daemon.support.DaemonLoader.start(DaemonLoader.java:243)
Caused by: com.google.inject.CreationException: Guice creation errors:

1) Error injecting constructor, java.lang.NullPointerException
  at com.ubnt.airvision.system.SystemConfiguration.<init>(Unknown Source)
  at com.ubnt.airvision.A.String.configure(Unknown Source)
  while locating com.ubnt.airvision.system.SystemConfiguration

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:435)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:183)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at com.google.inject.Guice.createInjector(Guice.java:72)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at com.ubnt.airvision.Main.getInjector(Unknown Source)
	at com.ubnt.airvision.Main.initializeApp(Unknown Source)
	at com.ubnt.airvision.Main.start(Unknown Source)
	... 5 more
Caused by: java.lang.NullPointerException
	at com.ubnt.common.ooOO.A.super(Unknown Source)
	at com.ubnt.airvision.system.SystemConfiguration.o00000(Unknown Source)
	at com.ubnt.airvision.system.SystemConfiguration.<init>(Unknown Source)
	at com.ubnt.airvision.system.SystemConfiguration$$FastClassByGuice$$90dc632.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:60)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:204)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:198)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:198)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:179)
	... 12 more
Cannot start daemon
java_start failed
Service exit with a return value of 5
</code>
</pre>
</details>

This is after creating a new directory, and running the docker run command for the first time

**Comment by fryfrog** [comment]
What label are you using, `:latest` probably? Can you show your full `docker run` command?

**Comment by fryfrog** [comment]
Not a lot of useful information to help and you've not come back, I'm gonna close.
