### ISSUE TITLE
Running network controller and video on the same machine

### ISSUE THREAD

**Issue by patvdleer** [pducharme/UniFi-Video-Controller#197]
At first I found the following:

I've been diving into the issue and found that it looks like it's ignoring the `system_ip` setting:

![image](https://user-images.githubusercontent.com/1138136/102990900-789cb680-4518-11eb-81e8-26ef592fbd34.png)

The container is set to `host`

```
# unifi-video v3.10.13
#Wed Dec 23 11:03:50 CET 2020
is_default=false
uuid=4293384a-a608-4ea1-9604-d8xxxxx
# app.http.port = 7080
# app.https.port = 7443
# ems.liveflv.port = 6666
# ems.livews.port = 7445
# ems.livewss.port = 7446
system_ip=192.168.178.38
```

error logs:
```
1608722212.953 2020-12-23 12:16:52.953/CET: ERROR  [uv.common] Failed initializing discovery server in DiscoveryServer
java.net.BindException: Address already in use (Bind failed)
	at java.net.PlainDatagramSocketImpl.bind0(Native Method) ~[?:1.8.0_265]
	at java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:93) ~[?:1.8.0_265]
	at java.net.DatagramSocket.bind(DatagramSocket.java:392) ~[?:1.8.0_265]
	at java.net.MulticastSocket.<init>(MulticastSocket.java:172) ~[?:1.8.0_265]
	at java.net.MulticastSocket.<init>(MulticastSocket.java:136) ~[?:1.8.0_265]
	at com.ubnt.A.super.oOOO.String.new(Unknown Source) ~[airvision.jar:?]
	at com.ubnt.A.super.oOOO.String.run(Unknown Source) [airvision.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
```

Checking my ports I found that the network controller is also using the `10001` port.

So now I need to either see if I can run video on `10002` or get it to run on a different ip. 

Anyone else running into this problem?

**Comment by patvdleer** [comment]
So I setup an additional IP for the server itself, 

`/etc/hosts`
```
192.168.178.38  unifi-video
```

`/etc/network/interfaces`
```
# The primary network interface
auto enp0s31f6
iface enp0s31f6 inet static
address 192.168.178.38
netmask 255.255.255.0
broadcast 192.168.178.255
network 192.168.178.0

auto enp0s31f6:0
iface enp0s31f6:0 inet static
address 192.168.178.8
netmask 255.255.255.0
broadcast 192.168.178.255
network 192.168.178.0
```

I configured the network controller from `(0.0.0.0:)10001` to bind to `192.168.178.8:10001`
and tried to set the video controller to `192.168.178.38:10001` in bridge mode but the ip problem returns...

![image](https://user-images.githubusercontent.com/1138136/102993909-53ab4200-451e-11eb-9b99-b8660fc45eef.png)


Using it in host mode it tries to bind to ip 192.168.178.8 (or 0.0.0.0, not sure but same result)
