### ISSUE TITLE
Need to specify specific OpenJDK version

### ISSUE THREAD

**Issue by dalanmiller** [pducharme/UniFi-Video-Controller#199]
Error when booting current version:
```
unifi-video-controller    | java.lang.ClassFormatError: Illegal method name "new.super" in class com/ubnt/airvision/Main
unifi-video-controller    | 	at java.lang.ClassLoader.defineClass1(Native Method)
unifi-video-controller    | 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
unifi-video-controller    | 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
unifi-video-controller    | 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
unifi-video-controller    | 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
unifi-video-controller    | 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
unifi-video-controller    | 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
unifi-video-controller    | 	at java.security.AccessController.doPrivileged(Native Method)
unifi-video-controller    | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
unifi-video-controller    | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
unifi-video-controller    | 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
unifi-video-controller    | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
unifi-video-controller    | 	at org.apache.commons.daemon.support.DaemonLoader.load(DaemonLoader.java:151)
unifi-video-controller    | Cannot load daemon
unifi-video-controller    | java_load failed
unifi-video-controller    | Service exit with a return value of 3
```

https://www.reddit.com/r/Ubiquiti/comments/l30jm5/unifi_video_31013_not_compatible_with_openjdk_180/gmut624/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by nstankov-bg** [comment]
I have since proposed a fix.
https://github.com/pducharme/UniFi-Video-Controller/pull/200
